name: whisper-chat-app

build:
  type: docker
  dockerfile: Dockerfile

routes:
  - path: /

envs:
  - key: FIREBASE_KEY_JSON
    value: |
      {
        "type": "service_account",
        "project_id": "chart-9e5cb",
        "private_key_id": "6f540d142ac995266c55d185bd673d4f529afde6",
        "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJOR1nwnLEiljS\\nGwAISgaooeYthuvf2ilCw6eotbRBBkAJbTbE7W9oyi63BfBfyHnJ7xtgsfIDUA4c\\nbUANioBGJq54hJKnBqrBAD9qO/TUYdKORqAdlm47wKSDmgOnM+y4YgIPZBCfZ9dR\\nLK/c2OcLh8U8ELfphCZ/qUa4An+mTNDrGbcn1WSFqHEWkWal/tU+JBve1C4HINoI\\nAaHCwRBKrZ/UgPFcOAGjGyafXsAs3BEKlFdbF7cLG3BU31OcBrA/J72xo/VAJ8FE\\nLvyx2whP1/xMMzcf62vGa/9eYT6NXLQeASP+MKStBDuWDdTgTr9hjgCJx0yAFbLh\\nza5reJ3vAgMBAAECggEAP8txRKeTrjb0UOxJdtdNRCJL8OwhFO+7/BQ+r9CnrKPY\\nIoTzA70JAK504Aasfhl3byt0wRO5WA6F4sJKN+DMqTDzSHczbWvCL/0tnbcTeE/p\\nKr0+XxMFsMDzB1wJQ3XFW3GLGKkPUhJgY7ZorPpBSdkKEXB1dj203O1kY8s7ABQz\\nBqYoj1zYTM4dJpwRf0V4J6/gefZ6hzb3aHcYpIaX5zF3nIHPFEpmTxIswlSysmbw\\nyrYRbeE2MHPneAmszktDbtGDr6t9rVsqm3WG8kz3thzOBqrMuok6N6vjEWJRuIDJ\\n6fVs44pe2QIfzz5OCY46CN+VuJVFu8e4dkIB4DjYrQKBgQD3cD3YheB/muzRc9el\\nYyGI9pR0pAV2wob/XQvXr94WSYIwxNavrFRkgXLejI5pg7HLn4gTk94ido/wW5pI\\nGlhofDdE3ZIrecrPfebBTlYGR9SU8AQLiD4dfWofccVbzNS8ZkKTKZ6kFtUWKO7u\\n+4nIeYunx1iJLIQz+3ia/5nQJQKBgQDQL4HkkKDWlF6pejYdpv9vK7WGqs/xIy4n\\nlSbf/cpGGH0hed35FyO4BcAcy7wAmOS9wwi27l34PJ7308Ab9i//17m98N4gxoTd\\nb+j/cWTjCv6qI+9OOQVyf3cGs4oTDXtgaAqssEge5EZvZz3+KV6c1qD/Rql02Nhr\\nLiIp7EI/gwKBgQCIvEXw+UpuObbUqCdrBbTqcxjmvB0o26auR0TcFBuuRUDkomHh\\nAmJAiChqQ1IPjO8bjzUrXHNMqCgysuw3HBfu5XXFYIv96nfg4bo66IcxQVCAXYJe\\nvRNWSI/0gHKHoFGPKxNvL3izRMrMTCJ9fhNN7Zz3Qnnyk98ausSTItxk4QKBgA86\\nimvn0Hwh2lLXZ8H/h0vgjKTPNerTwfqPRIq6C+PYwr6CJaSk9q3tbcItfREmHgVr\\nkOWgxir0dER4ruLcvWIfq6yjQ/xtySZRm1+kMdcR5NMZUdYNAcMAY/qPg5glMlM5\\nCR7cvknUNPrNOJGxAQTEBn7l8ltjyWD9vO4IJEh1AoGAcg1VLo6pxKN274dcOy7V\\nMihBEvHnAKE7LiOMxz8tWcKoFszI/ZNCOe9Il528kqhnNJn8WDPvYDvP6c8VgUTS\\nuXmpej6EgNqD/CWfbNYgGzoo5+H6q+ObFIEO7iYXTO3fCPb8x9qFZtN02Xi5JM6W\\nPYaMItkYsd7VXvCLh/oYV9I=\\n-----END PRIVATE KEY-----\\n",
        "client_email": "firebase-adminsdk-fbsvc@chart-9e5cb.iam.gserviceaccount.com",
        "client_id": "110603861136066117503",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40chart-9e5cb.iam.gserviceaccount.com",
        "universe_domain": "googleapis.com"
      }
